### ISSUE TITLE
Transmission Error Message When Downloading torrent

### ISSUE THREAD

**Issue by MachineSaver** [EdyTheCow/docker-media-center#4]
Can you help me resolve transmission torrent client running from a docker compose file which looks like:

**The error when attempting to download the torrent:** Couldn't get '/data/downloads/complete/filename: Permission denied (13)

<img width="708" alt="268374727-a2abdaa8-9da3-491f-80c0-cec7ff5150b8" src="https://github.com/EdyTheCow/docker-media-center/assets/64045074/794e85dc-c5a2-4af5-a44f-52b856587170">

**docker-compose.yml**

version: "3.7"

networks:
  global:
    external: true
  local:
    external: false

services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    #security_opt: # Required for Docker versions below 20.10.10, update Docker for long term solution. Source: https://docs.linuxserver.io/faq#jammy
    #  - seccomp=unconfined
    networks:
      - global
      - local
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${SERVICES_DIR}/jellyfin:/config
      - ${DATA_DIR}/media:/data/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dmc-jellyfin.rule=Host(`${SUB_DOMAIN_JELLYFIN}.${DOMAIN}`)"
      - "traefik.http.routers.dmc-jellyfin.tls=true"
      - "traefik.http.services.dmc-jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.dmc-jellyfin.tls.certresolver=letsencrypt"
      - "traefik.docker.network=global"

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    networks:
      - global
      - local
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ={TIMEZONE}
    volumes:
      - ${SERVICES_DIR}/transmission:/config
      - ${DATA_DIR}/downloads:/data/downloads
    ports:
      - 51413:51413 # Torrent port TCP
      - 51413:51413/udp # Torrent port UDP
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dmc-transmission.rule=Host(`${SUB_DOMAIN_TRANSMISSION}.${DOMAIN}`)"
      - "traefik.http.routers.dmc-transmission.tls=true"
      - "traefik.http.services.dmc-transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.dmc-transmission.tls.certresolver=letsencrypt"
      - "traefik.docker.network=global"
      # Basic auth
      - "traefik.http.middlewares.dmc-auth.basicauth.usersfile=/.htpasswd"
      - "traefik.http.routers.dmc-transmission.middlewares=dmc-auth"

**Comment by EdyTheCow** [comment]
Looks like there's something wrong with file permissions. It could be as simple as defining correct IDs for `ENV_PUID` and `ENV_PGID`. By default both of them are set to 1000, to find your user and group IDs type `id` into the terminal and you should get something like this:  

![8mhLL1X](https://github.com/EdyTheCow/docker-media-center/assets/5132667/20300dd1-a35a-47d2-a27b-04b41635f93e)

Now in `/dmc/compose/.env` set your `uid` as `ENV_PUID` and `gid` as `ENV_PGID`. That should make the container match your file permissions with the host.

**Comment by MachineSaver** [comment]
Eddy,
I tried this but the id command results in a ENV_puid and ENV_guid of 1000 which are the values set in the .env file. Despite doing this I still have permission errors when using transmission to download and save to data/downloads/complete.

This question might show some of ignorance of the way docker handles the memory/folder which will store the movie/tv files that are served to jellyfin, but if I have the containers running can I simply load the video files into this folder:
/home/username/docker-media-center/dmc/data/downloads?

Is this also the location that transmission is depositing downloads as set by the "download to" setting within transmission to?

/data/downloads/complete

Or would you want to set that value in the transmission UI to a complete path such as:
/home/username/docker-media-center/dmc/data/downloads?

**Comment by EdyTheCow** [comment]
If you want to change the path for all media files, simply change the `DATA_DIR` variable in `.env` file. For your mentioned path, you would want to set it as `/home/username/docker-media-center/dmc/data`. 

Do not change any paths inside Transmission unless otherwise stated in the guide. Transmission does not see your home directory or any of your files outside its container. The defined volume [`${DATA_DIR}/downloads:/data/downloads`](https://github.com/EdyTheCow/docker-media-center/blob/e7352662c933b2718fa5452d1e4f255ae41818a7/dmc/compose/docker-compose.yml#L46) in `docker-compose.yml` simply mounts path `/data/downloads` from inside of Transmission container to outside the container path `${DATA_DIR}/downloads`. This also means the download path within Transmission should be set to `/data/downloads`, otherwise Docker won't be able to mount the correct directory as defined in volumes. 

So if you set DATA_DIR to `/home/username/docker-media-center/dmc/data` the Transmission downloads folder will show up in `/home/username/docker-media-center/dmc/data/downloads`.
